---
- hosts: appdbs
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
    - name: configure yum repo
      include_role:
        name: common

    - name: install tomcat
      package:
        name: tomcat
        state: latest

    - name: create tomcat directory
      file:
        path: "/usr/share/tomcat/webapps/{{ item }}"
        state: directory
      with_items:
        - ROOT
        - ansible

    - name: copy static index.html to tomcat webapps/ansible/index.html
      template:
        src: "templates/{{ item.src }}"
        dest: "/usr/share/tomcat/webapps/ROOT/index.html"
        mode: 0644
      with_items:
        - {src: 'index.html.j2', groups: 'ROOT' }
    
    - name: start and enable tomcat
      service:
        name: tomcat
        enabled: yes
        state: started


  